### PR TITLE
v2  fixes #35

### LINKED ISSUE #35: v2 plan
Here's what I'm thinking about for the next major release (2.0.0):

* require node v12.17 and up
* switch to pure es module
* drop commonjs
* switch to es6 everywhere (`const`, `let`, `spread`, `destructuring`,  etc.)
* update all deps

These are just my current musings. Open for thoughts/ideas/suggestions.

### PR DESCRIPTION
**Pull request by mreinstein**
* convert to pure es module
* remove old versions of node (< 12)
* enforce node version as  a required thing via `.npmrc`
* update all deps
* update readme
* add changelog

### CODE REVIEW

**Review by dblock — APPROVED** [review]
LGTM!

**Comment by tejashah88** [comment]
@mreinstein It seems that the automated Travis builds are not happening due to a change in their pricing structure and website. Can you verify the tests on your machine and update them as needed?

**Comment by mreinstein** [comment]
Yeah I saw that too. I was trying to update to travis.com but that didn't solve it. I guess time to expore github actions?

**Comment by tejashah88** [comment]
@mreinstein Thank you for your work! I guess it's indeed time to explore GitHub actions

**Comment by mreinstein** [comment]
I started switching all my personal projects over to it.  I do hesitate a little, relying on more github services/features because it means I'm more tied to them, but I guess the same could be said of travis, and it's definitely a simpler integration.

**Comment by tejashah88** [comment]
I agree with your sentiment. It's a limitation that we'll have to accept on the name of using free services and a relatively easy dev experience.

**Pull request merged**
