### PR TITLE
Fix #14: Middleware hangs if rawBody is already parsed

### LINKED ISSUE #14: req.on('end', function() {}) never fires, middleware hangs
With another body-parser above it (see https://github.com/alexa-js/alexa-app/issues/152) the middleware hangs. The middleware needs to read and process the entire request body in order for the validation to work, and express doesn't expose that on the request object directly. So it accumulates the whole data of the request before any processing happens. That doesn't explain why the request would hang.

### PR DESCRIPTION
**Pull request by tejashah88**

### CODE REVIEW

**Comment by dblock** [comment]
I don't believe it does what you say it does until there's a test! And the existing test is relying on some externals. Show me a test that uses `body-parser` and that hangs without this change?

**Comment by tejashah88** [comment]
> Show me a test that uses body-parser and that hangs without this change?

Seems completely pointless since #14 is labeled as a "confirmed bug."

**Comment by dblock** [comment]
If I look at this diff I am not convinced that it fixes the issue. I could try it against that scenario in #14 that reproduces the issue, but there're no guarantees that you or someone else doesn't reintroduce this bug in a future version. Makes sense?

**Comment by dblock** [comment]
And to prove my point, here's a test that still hangs with this change, so it doesn't fix the bug.

https://github.com/dblock/alexa-verifier-middleware/commit/592cdedd52b3b90862b419e850ddc931ae775824

```js
test('with express.js and body-parser incorrectly mounted', function(t) {
  var express = require('express');
  var app = express();
  app.use(require('body-parser').json);
  app.use(verifier);
  var server = app.listen(3000);
  app.get('/', function(req, res) {
    res.status(200).send('ok');
  });
  var request = require('supertest');
  request(server)
    .get('/')
    .end(function (err, res) {
      t.equal(res.statusCode, 401);
      t.deepEqual(res.body, {
        "reason": "signature is not base64 encoded",
        "status": "failure"
      });
      server.close();
      t.end();
    });
});
```

**Comment by tejashah88** [comment]
This line: `app.use(require('body-parser').json);` is not correct because `.json` is a function that takes in a set of options ([original documentation](https://github.com/expressjs/body-parser#bodyparserjsonoptions)).

**Comment by dblock** [comment]
Ah yes, you're right.

Now I cannot get it to hang in a test. But that bug was real, no?

**Comment by tejashah88** [comment]
Technically yes, although the [`.json`](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L50) function itself is not a middleware function.

**Comment by tejashah88** [comment]
Moving on, can this PR be merged, since #21 should account for the extra test?

**Comment by dblock** [comment]
Except that the test in #21 doesn't hang, so I am unclear how this change here fixes anything?

**Comment by tejashah88** [comment]
I think the `return` statement [here](https://github.com/alexa-js/alexa-verifier-middleware/pull/19/files#diff-168726dbe96b3ce427e7fedce31bb0bcL12) helped fix the bug. Basically, you said that adding a return statement should abort the request immediately. If you remove it, you'd need to call `next()`, to tell express that the middleware is done, otherwise it hangs.

> If the current middleware function does not end the request-response cycle, it must call next() to pass control to the next middleware function. Otherwise, the request will be left hanging.

Source: http://expressjs.com/en/guide/using-middleware.html

**Comment by dblock** [comment]
Nope, you're guessing again :) I removed it and the test in #19 doesn't hang.

Anyway, I think this change is still right, having looked at the body-parser code it only checks `_body` and the rest is very specific to this library. I'll merge, lets move on.

**Pull request merged**
